Product crud 2
matsevich/trucco pull request #15
Opened 2021-04-05 06:34 UTC by matsevich

[Create CRUD for admin Products](https://github.com/matsevich/trucco/projects/1#card-52764687)
![Screenshot from 2021-04-05 09-32-04](https://user-images.githubusercontent.com/57501008/113545007-0bf28700-95f2-11eb-8ec8-6ae1c62b0901.png)
![Screenshot from 2021-04-05 09-32-28](https://user-images.githubusercontent.com/57501008/113545008-0d23b400-95f2-11eb-845c-71e06bc918e8.png)
![Screenshot from 2021-04-05 09-32-40](https://user-images.githubusercontent.com/57501008/113545009-0dbc4a80-95f2-11eb-9823-f5fb2118d33f.png)
![Screenshot from 2021-04-05 09-32-51](https://user-images.githubusercontent.com/57501008/113545010-0dbc4a80-95f2-11eb-9015-c5e73bf171a5.png)
![Screenshot from 2021-04-05 09-33-09](https://user-images.githubusercontent.com/57501008/113545011-0e54e100-95f2-11eb-93cf-de7494e93b7a.png)
![Screenshot from 2021-04-05 09-33-14](https://user-images.githubusercontent.com/57501008/113545012-0eed7780-95f2-11eb-8fb8-4e3cf151ccd4.png)
![Screenshot from 2021-04-05 09-33-36](https://user-images.githubusercontent.com/57501008/113545013-0f860e00-95f2-11eb-92ec-e27fa3ef1129.png)

2021-04-06 19:20 UTC, denys281 requested changes

2021-04-06 19:20 UTC, denys281 commented on app/controllers/prices_controller.rb
> +  def update # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
Why you disabled metrics here, in case you have offences you need to fix it

2021-04-06 19:20 UTC, denys281 commented on app/controllers/prices_controller.rb
> +      if (identic = @product.prices.where(
Should be pulled out from controller, to service, query object, whatever

2021-04-06 19:20 UTC, denys281 commented on app/controllers/products_controller.rb
> +    if (existing_product = Product.find_by(name: @product.name))
Move this also, tooooooooooo muchhhh logic here, it is hard to read.

2021-04-17 19:38 UTC, denys281 requested changes

2021-04-17 19:38 UTC, denys281 commented on app/controllers/prices_controller.rb
> +      PriceUpdater.new(@product, @price).call
I think you should check if `ProductUpdater` returns true or false, I recommend you take a look  to  https://github.com/collectiveidea/interactor-rails

2021-04-17 19:38 UTC, denys281 commented on app/controllers/products_controller.rb
> +    @products = Product.all
Pagination?

2021-04-17 19:38 UTC, denys281 commented on app/controllers/products_controller.rb
> +
From line 18 to 26 could be moved to separate service

2021-04-17 19:38 UTC, denys281 commented on app/helpers/prices_helper.rb
> +module PricesHelper
delete if it is empty

2021-04-17 19:38 UTC, denys281 commented on app/helpers/products_helper.rb
> +  def behavior_existing_product_price(product, existing_product, product_price)
Logic shouldn't be in helper.

2021-04-17 19:38 UTC, denys281 commented on app/services/price_updater.rb
> +    @identic = product.prices.where(
could be moved to scope in model

2021-04-17 19:38 UTC, denys281 commented on app/services/product_price_handler.rb
> +      product_price.quantity, product.name, product_price.buy_price.format, product_price.sell_price.format
flash messages should be on controllers level. You could do some presenter or whatever, but services only for business logic, and that should return true/false, and some additional data. But flash shouldn't be  here

2021-04-17 19:38 UTC, denys281 commented on app/services/product_price_handler.rb
> +  include ProductsHelper
remove it, it is wrong :)

2021-04-18 09:45 UTC, matsevich commented on app/controllers/prices_controller.rb
> +      PriceUpdater.new(@product, @price).call
@denys281  І think that I don't want to use pagination here, on the index page, it will be not handy

2021-04-18 09:46 UTC, matsevich commented on app/controllers/products_controller.rb
> +    @products = Product.all
@denys281  І think that I don't want to use pagination here, on the index page, it will be not handy

2021-05-30 13:13 UTC, merged